### ISSUE TITLE
Long running processes and Invalid Data Source error

### ISSUE THREAD

**Issue by jpudney** [fuel/core#1587]
Hey,

I've a long running process that appears to be failing to re-connect to the database. For some time now I believed that it was the [infamous](http://fuelphp.com/forums/discussion/10980/problem-with-daemon) [server has gone away](http://forums.laravel.io/viewtopic.php?id=10745) error.

Below is the stack trace from the exceptions that's thrown (some directories omitted and replaced with ...):

``` php
Uncaught exception Fuel\Core\Database_Exception: invalid data source name
Callstack: 
#0 .../fuel/app/classes/database/pdo/connection.php(246): Database_PDO_Connection->connect()
#1 .../fuel/core/classes/database/query.php(263): Database_PDO_Connection->query(1, 'SELECT `parent_...', false)
#2 .../fuel/app/classes/worker/processor.php(107): Fuel\Core\Database_Query->execute()
#3 .../fuel/app/classes/worker/processor.php(200): Worker\Processor->getUserId(...)
#4 .../fuel/app/classes/worker/processor.php(58): Worker\Processor->getSettings(...)
#5 .../fuel/app/classes/worker/processor.php(31): Worker\Processor->ordersCreate(Object(stdClass))
#6 .../fuel/app/tasks/worker.php(26): Worker\Processor->process('{"webhook":{"to...')
#7 [internal function]: Fuel\Tasks\{closure}(Object(PhpAmqpLib\Message\AMQPMessage))
#8 .../fuel/vendor/videlalvaro/php-amqplib/PhpAmqpLib/Channel/AMQPChannel.php(717): call_user_func(Object(Closure), Ob
ject(PhpAmqpLib\Message\AMQPMessage))
#9 [internal function]: PhpAmqpLib\Channel\AMQPChannel->basic_deliver(Object(PhpAmqpLib\Wire\AMQPReader), Object(PhpAmqpLib\Message\AMQP
Message))
#10 .../fuel/vendor/videlalvaro/php-amqplib/PhpAmqpLib/Channel/AbstractChannel.php(108): call_user_func(Array, Object(
PhpAmqpLib\Wire\AMQPReader), Object(PhpAmqpLib\Message\AMQPMessage))
#11 .../fuel/vendor/videlalvaro/php-amqplib/PhpAmqpLib/Channel/AbstractChannel.php(261): PhpAmqpLib\Channel\AbstractCh
annel->dispatch('60,60', '?amq.ctag-MmdtR...', Object(PhpAmqpLib\Message\AMQPMessage))
#12 .../fuel/app/tasks/worker.php(35): PhpAmqpLib\Channel\AbstractChannel->wait()
#13 .../fuel/core/base.php(428): Fuel\Tasks\Worker::run()
#14 .../fuel/packages/oil/classes/refine.php(106): call_fuel_func_array(Array, Array)
#15 [internal function]: Oil\Refine::run('worker', Array)
#16 .../fuel/packages/oil/classes/command.php(125): call_user_func('Oil\Refine::run', 'worker', Array)
#17 .../oil(57): Oil\Command::init(Array)
#18 {main}

Previous exception: 
Uncaught exception PDOException: invalid data source name
Callstack: 
#0 .../fuel/app/classes/database/pdo/connection.php(95): PDO->__construct('', NULL, NULL, Array)
#1 .../fuel/app/classes/database/pdo/connection.php(246): Database_PDO_Connection->connect()
#2 .../fuel/core/classes/database/query.php(263): Database_PDO_Connection->query(1, 'SELECT `parent_...', false)
#3 .../fuel/app/classes/worker/processor.php(107): Fuel\Core\Database_Query->execute()
#4 .../fuel/app/classes/worker/processor.php(200): Worker\Processor->getUserId(...)
#5 .../fuel/app/classes/worker/processor.php(58): Worker\Processor->getSettings(...)
#6 .../fuel/app/classes/worker/processor.php(31): Worker\Processor->ordersCreate(Object(stdClass))
#7 .../fuel/app/tasks/worker.php(26): Worker\Processor->process('{"webhook":{"to...')
#8 [internal function]: Fuel\Tasks\{closure}(Object(PhpAmqpLib\Message\AMQPMessage))
#9 .../fuel/vendor/videlalvaro/php-amqplib/PhpAmqpLib/Channel/AMQPChannel.php(717): call_user_func(Object(Closure), Ob
ject(PhpAmqpLib\Message\AMQPMessage))
#10 [internal function]: PhpAmqpLib\Channel\AMQPChannel->basic_deliver(Object(PhpAmqpLib\Wire\AMQPReader), Object(PhpAmqpLib\Message\AMQ
PMessage))
#11 .../fuel/vendor/videlalvaro/php-amqplib/PhpAmqpLib/Channel/AbstractChannel.php(108): call_user_func(Array, Object(
PhpAmqpLib\Wire\AMQPReader), Object(PhpAmqpLib\Message\AMQPMessage))
#12 .../fuel/vendor/videlalvaro/php-amqplib/PhpAmqpLib/Channel/AbstractChannel.php(261): PhpAmqpLib\Channel\AbstractCh
annel->dispatch('60,60', '?amq.ctag-MmdtR...', Object(PhpAmqpLib\Message\AMQPMessage))
#13 .../fuel/app/tasks/worker.php(35): PhpAmqpLib\Channel\AbstractChannel->wait()
#14 .../fuel/core/base.php(428): Fuel\Tasks\Worker::run()
#15 .../fuel/packages/oil/classes/refine.php(106): call_fuel_func_array(Array, Array)
#16 [internal function]: Oil\Refine::run('worker', Array)
#17 .../fuel/packages/oil/classes/command.php(125): call_user_func('Oil\Refine::run', 'worker', Array)
#18 .../oil(57): Oil\Command::init(Array)
#19 {main}
Error: invalid data source name in .../fuel/app/classes/database/pdo/connection.php on 121
```

The most interesting line from the stack trace is `#0 .../fuel/app/classes/database/pdo/connection.php(95): PDO->__construct('', NULL, NULL, Array)`

Stepping through the code, when a 2006 error occurs we disconnect and then attempt to connect to the db again. However, and I hadn't noticed this line before (but it's definitely been there all along), there's a [call that clears the connection details](https://github.com/fuel/core/blob/1.8/develop/classes/database/pdo/connection.php#L74) which is what leads to `#0 .../fuel/app/classes/database/pdo/connection.php(95): PDO->__construct('', NULL, NULL, Array)`

I need to carry out some more testing but I'm certain that this is the culprit for a long process bombing out when needing to re-connect to the database.

Can this be considered a bug?

Thanks.

**Comment by huglester** [comment]
Hello

It is related to #1583 

yes, Invalid data source is 'Mysql has gone away in php_mysql, in php_mysqli it is probably 2006 error or something like that

**Comment by WanWizard** [comment]
All drivers seem to do this. The idea behind it is that you don't want to password to be kept in a class property, to prevent exposure. But that will indeed mean a reconnect will fail.

It's old kohana code, Fuel's error handling doesn't dump data, so I don't see an immediate security risk of keeping the password in the class property. Yes, if your app got hacked they could get it, but in that case reading the config file is probably easier...

**Comment by WanWizard** [comment]
I'll close this issue, discussion continues in #1583
