### ISSUE TITLE
Fatal error: Uncaught Error: Call to undefined method Error::error_handler() stack trace

### ISSUE THREAD

**Issue by ji1t** [fuel/core#2121]
Fatal error: Uncaught Error: Call to undefined method Error::error_handler() in /home/hostname/public_html/folder/fuel/core/bootstrap.php:48 Stack trace: #0 /home/hostname/public_html/folder/fuel/core/vendor/phpseclib/Crypt/AES.php(467): {closure}(8192, 'Function mcrypt...', '/home/hostname/...', 467, Array) #1 /home/hostname/public_html/folder/fuel/core/vendor/phpseclib/Crypt/AES.php(279): PHPSecLib\Crypt_AES->_mcryptSetup() #2 /home/hostname/public_html/folder/fuel/core/classes/crypt.php(107): PHPSecLib\Crypt_AES->encrypt('a:3:{i:0;a:6:{s...') #3 /home/hostname/public_html/folder/fuel/core/classes/session/driver.php(459): Fuel\Core\Crypt::encode('a:3:{i:0;a:6:{s...') #4 /home/hostname/public_html/folder/fuel/core/classes/session/cookie.php(111): Fuel\Core\Session_Driver->_set_cookie(Array) #5 [internal function]: Fuel\Core\Session_Cookie->write('', Array) #6 /home/hostname/public_html/folder/fuel/core/classes/event/instance.php(163): call_user_func(Array, '', Array) #7 /home/hostname/public_html/wor in /home/hostname/public_html/folder/fuel/core/bootstrap.php on line 48

**Comment by WanWizard** [comment]
This suggests that you're using a Fuel version < 1.8, in combination with PHP 7+. You need to upgrade to at least 1.8 get PHP 7 compatibility.

Alternatively, you have a class called "Error" in the global namespace.
